spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/codementor
spring.datasource.username=codementor
spring.datasource.password=codementor123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Gemini API config
gemini.api.key=${AIzaSyAdNIHmnzbdRbFcZXzWgfijmxIXAWAZSC0}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.model=gemini-2.5-flash

# JWT config
jwt.secret=change-this-to-a-very-long-random-string-at-least-256-bits-or-32-characters-long
jwt.expiration=86400000